package VeryGoodViroGame.Equipment;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Equipment.EquipmentGloves.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

import VeryGoodViroGame.Agent.Agent;
import VeryGoodViroGame.EntityManager;
import VeryGoodViroGame.Logger;
import VeryGoodViroGame.Virologist;

/**
 * A kesztyű védőfelszerelést reprezentálja, az ezt viselő virológusra
 * kent ágens visszadobódik arra a virológusra aki felkente.
 */
public class EquipmentGloves extends Equipment
{
    private int remainingHealth = 3;
    
    
    /**
     * (InvItem metódus) hamis érték visszaadásával blokkolja
     * az ágens felkenődését, illetve véletlenszerűen, előre
     * megadott eséllyel visszakeni az ágenst az eredeti kenőre.
     *
     * @param agent  maga az ágens amivel kenni próbálnak
     * @param source az ágenst felkenő virológus
     */
    public boolean CanAgentBeApplied(Agent agent, Virologist source)
    {
        agent.Apply(host, source);
        remainingHealth--;
        if(remainingHealth == 0)
        {
            host.DestroyEquipment(this);
        }
        return false;
    }
    
    @Override
    public String toString()
    {
        return super.toString() + "\n\tremainingHealth: " + remainingHealth;
    }
}
