using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.Dance.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Egy vírust reprezentál a játékban, amíg egy virológuson hatást gyakorol,
    /// a virológus fel-alá mozog, ekkor a játékban nem irányítható.
    /// </summary>
    public class Dance : Agent
    {
        public Dance(): base()
        {
            strategy = new MSVitusDance();
        }
    }
} //
