using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.EquipmentGloves.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// A kesztyű védőfelszerelést reprezentálja, az ezt viselő virológusra
    /// kent ágens visszadobódik arra a virológusra aki felkente.
    /// </summary>
    public class EquipmentGloves : Equipment
    {
        private int remainingHealth = 3;
        /// <summary>
        /// (InvItem metódus) hamis érték visszaadásával blokkolja
        /// az ágens felkenődését, illetve véletlenszerűen, előre
        /// megadott eséllyel visszakeni az ágenst az eredeti kenőre.
        /// </summary>
        /// <param name="agent">maga az ágens amivel kenni próbálnak</param>
        /// <param name="source">az ágenst felkenő virológus</param>
        public virtual bool CanAgentBeApplied(Agent agent, Virologist source)
        {
            Logger.NewFunctionCall(this, "CanAgentBeApplied");
            source.ApplyAgent(agent, host);
            remainingHealth--;
            if (remainingHealth == 0)
            {
                host.RemoveEquipment(this);
            }

            Logger.ReturnFunction();
            return false;
        }
    }
} //
