using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.EquipmentCoat.java
    //  @ Date : 2022. 03. 27.
    //  @ Author :
    //
    //
    /// <summary>
    /// A védőköpeny védőfelszerelést reprezentálja,
    /// az ezt viselő virológusra kent ágenseket tartja távol 82,3%-os hatásfokkal.
    /// </summary>
    public class EquipmentCoat : Equipment
    {
        /// <summary>
        /// (InvItem metódus) véletlenszerűen, előre megadott eséllyel blokkolja
        /// (hamis érték visszaadásával) az ágens felkenődését
        /// </summary>
        /// <param name="">agent az ágens amit fel akar kenni a felkeno virologus</param>
        /// <param name="">source az a virológus aki fel akarja kenni az agenst</param>
        public virtual bool CanAgentBeApplied(Agent agent, Virologist source)
        {
            Logger.NewFunctionCall(this, "Clone");
            bool answer = Logger.AskQuestion("Can the agent be applied to the virologist");
            Logger.ReturnFunction();
            return answer;
        }
    }
} //
