using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.FieldLab.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Egy speciális mező, a labort valósítja meg.
    /// Felelőssége a letapogathatóság biztosítása, valamint egy genetikai kód létezésének biztosítása.
    /// </summary>
    public class FieldLab : Field
    {
        private GeneticCode code;
        /// <summary>
        /// Ez a metódus valósítja meg a genetikai kód letapogatást.
        /// </summary>
        /// <param name="v">A virológus aki letapogatja a kódot.</param>
        public virtual void Interact(Virologist v)
        {
            Logger.NewFunctionCall(this, "Interact");
            v.LearnGeneticCode(code);
            Logger.ReturnFunction();
        }

        /// <summary>
        /// Ez a metódus valósítja beállítja a laborban fellelhető genetikai kódot.
        /// </summary>
        /// <param name="geneticCode">A kód amit beállítunk, hogy le lehessen tapogatni a laborban.</param>
        public virtual void SetCode(GeneticCode geneticCode)
        {
            Logger.NewFunctionCall(this, "setCode");
            code = geneticCode;
            Logger.ReturnFunction();
        }
    }
} //
