using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.FieldWarehouse.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Egy speciális mező, a raktárat valósítja meg.
    /// Felelőssége, adott raktárban anyagok létezésének
    /// valamint felvételének biztosítása.
    /// </summary>
    public class FieldWarehouse : Field
    {
        private Resource resources;
        /// <summary>
        /// Ez a metódus valósítja meg a feladat szövege szerinti felszerelés felvételét.
        /// </summary>
        /// <param name="v">A virológus aki a mezőn van.</param>
        public virtual void Interact(Virologist v)
        {
            Logger.NewFunctionCall(this, "Interact");
            v.AddResource(resources);
            Logger.ReturnFunction();
        }

        /// <summary>
        /// Ez a metódus valósítja meg, hogy az adott mezőn milyen felszerelés jelenjen meg.
        /// </summary>
        /// <param name="r">felszerelés</param>
        public virtual void SetResource(Resource r)
        {
            resources = r;
        }

        public override void Destroy()
        {
            resources = null;
        }
    }
} //
