using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.FieldBunker.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Egy mező, melyben egy felszerelés található, és vehető fel a virológusok által.
    /// Tárolja a tartalmazott felszerelést, mindaddig, amíg azt el nem távolítják.
    /// </summary>
    public class FieldBunker : Field
    {
        private Equipment equipment;
        private bool hasEquipment;
        /// <summary>
        /// Ez a metódus valósítja meg a feladat szövege szerinti felszerelés felvételét.
        /// </summary>
        /// <param name="v">A virológus aki a mezőn van.</param>
        public virtual void Interact(Virologist v)
        {
            Logger.NewFunctionCall(this, "Interact");
            if (Logger.AskQuestion("Does the bunker have equipment in it?"))
            {
                v.AddEquipment(equipment);
            }

            Logger.ReturnFunction();
        }

        /// <summary>
        /// Ez a metódus valósítja meg, hogy az adott mezőn milyen felszerelés jelenjen meg.
        /// </summary>
        /// <param name="equipment">felszerelés</param>
        public virtual void SetEquipment(Equipment equipment)
        {
            this.equipment = equipment;
            hasEquipment = true;
        }
    }
} //
