using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.Forget.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Egy vírust reprezentál a játékban, hatására a virológus elfelejti az addig megtanult genetikai kódokat.
    /// </summary>
    public class Forget : Agent
    {
        /// <summary>
        /// Hamissal tér vissza, hogy megakadályozza az adott virológust ágens kraftolásában.
        /// </summary>
        public virtual bool CanCraft()
        {
            Logger.NewFunctionCall(this, "CanCraft");
            Logger.ReturnFunction();
            return false;
        }
    }
} //
