using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.GameManager.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Ez a statikus osztály felelős az új játék elindításáért, és a játék befejezéséért.
    /// </summary>
    public class GameManager
    {
        static Map map;

        static List<Virologist> playableVirologists = new List<Virologist>();
        static EntityManager entityManager;

        /// <summary>
        /// Ez a metódus felelős a játék elindításáért.
        /// </summary>
        public static void StartGame()
        {
            Logger.NewFunctionCallLegacy("GameManager", "StartGame");
            map = new Map();
            map.GenerateMap();
            Logger.ReturnFunction();
        }

        /// <summary>
        /// Ez a metódus felelős a játék befejezéséért és a nyertes kihirdetéséért.
        /// </summary>
        /// <param name="winner">a játék győztese</param>
        public static void EndGame(Virologist winner)
        {
            Logger.NewFunctionCallLegacy("GameManager", "EndGame");
            Logger.ReturnFunction();
        }

        public static void RemoveFromPlayable(Virologist viro)
        {
            if (playableVirologists.Count == 0)
                EndGame(null);
            else
                playableVirologists.Remove(viro);
        }
    }
} //
