using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.GeneticCode.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Ez az osztály felelős a hozzájuk tartozó vakcinák és vírusok létrehozásáért,
    /// ezek reprezentálják a virológusok craftolási képességét is.
    /// </summary>
    public class GeneticCode
    {
        protected Resource cost;
        protected Agent a;
        /// <summary>
        /// Beállitja a cost értékét.
        /// </summary>
        /// <param name="r">az átadni kivánt resource érték</param>
        public virtual void SetCost(Resource r)
        {
            cost = r;
        }

        /// <summary>
        /// Beállitja az a (ágens amit a genetikai kód tartalmaz) értékét.
        /// </summary>
        /// <param name="agent">az átadni kivánt ágens</param>
        public virtual void SetAgent(Agent agent)
        {
            a = agent;
        }

        /// <summary>
        /// létrehozza az adott genetikai kódhoz tartozó vírust.
        /// </summary>
        /// <returns>a leklónozott ágens</returns>
        public virtual Agent CreateVirus()
        {
            Logger.NewFunctionCall(this, "CreateVirus");
            Agent clone = a.Clone();
            Timer.AddSteppable(clone);
            Logger.ReturnFunction();
            return clone;
        }

        /// <summary>
        /// létrehozza az adott genetikai kódhoz tartozó vakcinát.
        /// </summary>
        /// <returns>a leklónozott ágenshez tartozó vakcina</returns>
        public virtual Agent CreateVaccine()
        {
            Logger.NewFunctionCall(this, "CreateVaccine");
            Agent clone = a.Clone();
            Vaccine vaccine = new Vaccine(clone);
            Timer.AddSteppable(vaccine);
            Logger.ReturnFunction();
            return vaccine;
        }

        /// <summary>
        /// visszatér az adott ágens létrehozásához szükséges erőforrásbeli költséggel.
        /// </summary>
        /// <returns>a megadott kőltség</returns>
        public virtual Resource GetCost()
        {
            Logger.NewFunctionCall(this, "GetCost");
            Logger.ReturnFunction();
            return cost;
        }
    }
} //
