using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.iSteppable.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Ez egy interface, ami előírja, hogy milyen metódusokkal kell rendelkeznie azoknak az osztályoknak,
    /// melyek entitásai az idő hatására változnak.
    /// </summary>
    public interface iSteppable
    {
        /// <summary>
        /// Ezt a metódust kell implementálnia az időben változó entitásoknak.
        /// </summary>
        void Step();
    }
} //
