using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.MSParalyzed.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Ez az osztály a virológus bénult állapotában való mozgásáért felelős.
    /// </summary>
    public class MSParalyzed : iMoveStrategy
    {
        /// <summary>
        /// Ez a metódus akkor hívódik meg, amikor a virológus bénult állapotban mozogni próbál,
        /// ilyenkor nem tud mozogni.
        /// </summary>
        /// <param name="v">A virológus, akin a mozgást végrehajtjuk.</param>
        /// <param name="from">a Mező amiről mozgatjuk a virológust</param>
        /// <param name="to">a Mező amire mozgatjuk a virológust</param>
        public override void ExecuteMove(Virologist v, Field from, Field to)
        {
            Logger.NewFunctionCall(this, "ExecuteMove");
            Logger.ReturnFunction();
        }
    }
} //
