using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.SimpleMoveStrategy.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Ez az osztály felelős a virológus egyszerű mozgási stratégiájának megvalósításáért.
    /// </summary>
    public class MSSimple : iMoveStrategy
    {
        /// <summary>
        /// Ez a metódus végrehajtja az egyszerű mozgást, a virológus oda lép, ahova a játékos irányítja.
        /// </summary>
        /// <param name="v">A virológus, akin a mozgást végrehajtjuk.</param>
        /// <param name="from">a Mező amiről mozgatjuk a virológust</param>
        /// <param name="to">a Mező amire mozgatjuk a virológust</param>
        public void ExecuteMove(Virologist v, Field from, Field to)
        {
            Logger.NewFunctionCall(this, "ExecuteMove");
            from.RemoveViro(v);
            to.AcceptViro(v);
            Logger.ReturnFunction();
        }
    }
} //
