using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.Protect.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Egy vírust reprezentál a játékban, amíg egy virológuson hatást gyakorol,
    /// addig a virológusra nem lehet más ágenst rákenni.
    /// </summary>
    public class Protect : Agent
    {
        /// <summary>
        /// (InvItem metódus)  Mindig hamissal tér vissza, megakadályozva más ágensek kenését a virológuson.
        /// </summary>
        /// <param name="agent">az ágens amire vizsgáljuk, hogy felkenhető-e</param>
        /// <param name="source">a kenést végző virológus</param>
        /// <returns>boolean visszatérési érték, mindig hamis</returns>
        public virtual bool CanAgentBeApplied(Agent agent, Virologist source)
        {
            Logger.NewFunctionCall(this, "CanAgentBeApplied");
            Logger.ReturnFunction();
            return false;
        }
    }
} //
