using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.Resource.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Ez az osztály fogja össze a játékban összegyűjthető erőforrásokat, amiket craftolásra lehet használni.
    /// </summary>
    public class Resource
    {
        /// <summary>
        /// ami - aminosav
        /// nuki - nukleotid
        /// </summary>
        private int ami;
        private int nuki;
        /// <summary>
        /// Hozzáadja a paraméterként kapott erőforrásokat a meglévőkhöz.
        /// </summary>
        /// <param name="resource">paraméterként kapott erőforrás</param>
        public virtual void Add(Resource resource)
        {
            Logger.NewFunctionCall(this, "Add");
            Logger.ReturnFunction();
        }

        /// <summary>
        /// A paraméterként kapott erőforrásokat elveszi a meglévőektől.
        /// </summary>
        /// <param name="resource">paraméterként kapott erőforrás</param>
        public virtual void Remove(Resource resource)
        {
            Logger.NewFunctionCall(this, "Remove");
            Logger.ReturnFunction();
        } /*public void AddAmi(int ami)
        {
            throw new System.NotImplementedException();
        }

        public void RemoveAmi(int ami)
        {
            throw new System.NotImplementedException();
        }
        public void AddNuki(int nuki)
        {
            throw new System.NotImplementedException();
        }

        public void RemoveNuki(int nuki)
        {
            throw new System.NotImplementedException();
        }*/
    }
} //
