using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VeryGoodViroGame
{
    //
    //  Generated by StarUML(tm) Java Add-In
    //
    //  @ Project : Untitled
    //  @ File Name : VeryGoodViroGame.Vaccine.java
    //  @ Date : 2022. 03. 27.
    //  @ Author : 
    //
    //
    /// <summary>
    /// Ez az osztály felelős az azonos genetikai kód alapján készített vírusok semlegesítéséért.
    /// </summary>
    public class Vaccine : Agent
    {
        /// <summary>
        /// Az az ágens amihez a vakcinát létrehozzuk
        /// </summary>
        private Agent agentToCure;
        /// <summary>
        /// Vaccine osztály konstruktora, inicializálásért felelős
        /// </summary>
        /// <param name="agentToCure">az inicializálandó attribútum</param>
        public Vaccine(Agent agentToCure)
        {
            this.agentToCure = agentToCure;
        }

        /// <summary>
        /// A forrás virológus beadja a vakcinát a targetnek,
        /// és amennyiben a targeton épp hatást gyakorol egy ágens,
        /// melyet gyógyít a vakcina, a hatás megszűnik.
        /// </summary>
        /// <param name="source">az ágenst felkenő virológus</param>
        /// <param name="target">az a virológus akire felkenik az ágenst</param>
        public virtual void Apply(Virologist source, Virologist target)
        {
            Logger.NewFunctionCall(this, "Apply");
            target.RemoveItem(agentToCure);
            Timer.RemoveSteppable(agentToCure);
            Timer.RemoveSteppable(this);
            Logger.ReturnFunction();
        }
    }
} //
