//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Dance.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class Dance extends Agent
{
	public bool CanMove(Virologist v)
	{
	}
	
	public void Step();
}
