//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EquipmentSack.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class EquipmentSack extends Equipment
{
	public int GetMaxResource()
	{
	}
}
