//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EquipmentCoat.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class EquipmentCoat extends Equipment
{
	public bool CanAgentBeApplied(Agent agent, Virologist source)
	{
	}
}
