//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EquipmentGloves.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class EquipmentGloves extends Equipment
{
	public bool CanAgentBeApplied(Agent agent, Virologist source)
	{
	}
}
