//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Equipment.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public abstract class Equipment extends InvItem
{
}
