//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FieldLab.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class FieldLab extends Field
{
	private GeneticCode code;
	public bool Interact(Virologist v)
	{
	}
}
