//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FieldWarehouse.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class FieldWarehouse extends Field
{
	private Equipment equipment;
	public bool Interact(Virologist v)
	{
	}
}
