//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class Field
{
	public void AcceptViro(Virologist v)
	{
	}
	
	public bool Interact(Virologist v)
	{
	}
	
	public bool RemoveViro(Virologist v)
	{
	}
}
