//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FieldBunker.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class FieldBunker extends Field
{
	private Resource resources;
	public bool Interact(Virologist v)
	{
	}
}
