//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GameManager.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class GameManager
{
	private Map gameMap;
	private Map Map;
	public void StartGame()
	{
	}
	
	public void EndGame()
	{
	}
}
