//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : iSteppable.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public interface iSteppable
{
	public void Step();
}
