//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MoveStrategy.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class MoveStrategy
{
	public void ExecuteMove(Virologist v, Field from, Field to)
	{
	}
}
