//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Resource.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class Resource
{
	private int ami;
	private int nuki;
	public void Add(Resource resource)
	{
	}
	
	public bool Remove(Resource resource)
	{
	}
}
