//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SimpleMoveStrategy.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class SimpleMoveStrategy extends MoveStrategy
{
}
