//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vaccine.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class Vaccine extends Agent
{
	private Agent agentToCure;
	public void Apply(Virologist target)
	{
	}
	
	public void Step();
}
