package VeryGoodViroGame.Agent;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Agent.Dance.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import VeryGoodViroGame.DrawableComponent;
import VeryGoodViroGame.MoveStrategy.MSVitusDance;

/**
 * Egy vírust reprezentál a játékban, amíg egy virológuson hatást gyakorol,
 * a virológus fel-alá mozog, ekkor a játékban nem irányítható.
 */
public class Dance extends Agent
{
    public Dance()
    {
        super();
        strategy = new MSVitusDance();
        activeTimeDefault = 2;
    }
    
    @Override
    public String GetDrawString()
    {
        return "dance";
    }
}
