package VeryGoodViroGame.Agent;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Agent.GeneticCode.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

import VeryGoodViroGame.Agent.Agent;
import VeryGoodViroGame.Agent.Vaccine;
import VeryGoodViroGame.Logger;
import VeryGoodViroGame.Resource;
import VeryGoodViroGame.Timer;

/**
 * Ez az osztály felelős a hozzájuk tartozó vakcinák és vírusok létrehozásáért,
 * ezek reprezentálják a virológusok craftolási képességét is.
 */
public class GeneticCode
{
    protected Resource cost;
    protected Agent a;
    
    /**
     * Beállitja a cost értékét.
     *
     * @param r az átadni kivánt resource érték
     */
    public void setCost(Resource r)
    {
        cost = r;
    }
    
    /**
     * Beállitja az a (ágens amit a genetikai kód tartalmaz) értékét.
     *
     * @param agent az átadni kivánt ágens
     */
    public void setAgent(Agent agent)
    {
        a = agent;
    }
    
    /**
     * létrehozza az adott genetikai kódhoz tartozó vírust.
     *
     * @return a leklónozott ágens
     */
    public Agent CreateVirus()
    {
        Logger.NewFunctionCall(this, "CreateVirus");
        Agent clone = a.Clone();
        Timer.AddSteppable(clone);
        Logger.ReturnFunction();
        return clone;
    }
    
    /**
     * létrehozza az adott genetikai kódhoz tartozó vakcinát.
     *
     * @return a leklónozott ágenshez tartozó vakcina
     */
    public Agent CreateVaccine()
    {
        Logger.NewFunctionCall(this, "CreateVaccine");
        Agent clone = a.Clone();
        Vaccine vaccine = new Vaccine(clone);
        Timer.AddSteppable(vaccine);
        Logger.ReturnFunction();
        return vaccine;
    }
    
    /**
     * visszatér az adott ágens létrehozásához szükséges erőforrásbeli költséggel.
     *
     * @return a megadott kőltség
     */
    public Resource GetCost()
    {
        Logger.NewFunctionCall(this, "GetCost");
        Logger.ReturnFunction();
        return cost;
    }
    
    public boolean CompareCodes(GeneticCode code)
    {
        //TODO:valami ilyesmi kéne
        /*Class c = a.getClass();
        return code.a instanceof c;*/
        return false;
    }
}
