package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Agent.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public abstract class Agent extends InvItem implements iSteppable
{
	private int activeTime;
	public void Apply(Virologist target)
	{
	}
	
	public void Step()
	{
	}
	
}
