package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Agent.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public abstract class Agent extends InvItem implements iSteppable
{
    int activeTime;
    //Akin van
    Virologist host;
    iMoveStrategy strategy;
    
    public void Apply(Virologist source, Virologist target)
    {
    }
    
    public void Step()
    {
    }
    
    public Agent Clone()
    {
        return null;
    }
    
}
