package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Dance.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class Dance extends Agent
{
    public void Apply(Virologist source, Virologist target)
    {
        Logger.NewFunctionCall("Agent.Apply");
        Logger.ReturnFunction();
    }
}
