package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Dance.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


/**
 * Egy vírust reprezentál a játékban, amíg egy virológuson hatást gyakorol,
 * a virológus fel-alá mozog, ekkor a játékban nem irányítható.
 */
public class Dance extends Agent
{
    /**
     * Vitustánc vírus felkenéséért felelős metódus.
     *
     * @param  source az ágenst felkenő virológus
     * @param  target az a virológus akire felkenik az ágenst
     */
    public void Apply(Virologist source, Virologist target)
    {
        Logger.NewFunctionCall("Agent.Apply");
        Logger.ReturnFunction();
    }
}
