package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.EquipmentSack.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class EquipmentSack extends Equipment
{
    
    //Nem lehet, hogy inkánn int?
    //Mert ez az a mennyiség, amivel megnöveli a kapacitást
    private Resource amount;
    
    public int GetMaxResource()
    {
        Logger.NewFunctionCall("EquipmentSack.GetMaxResource");
        return 20;
    }
}
