package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Equipment.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

/**
 * A virológusok által felvehető felszerelések/ruhadarabok.
 * Alapvető célja, hogy ezeket az interaktív osztályok közös kezelését elősegítse.
 */
public abstract class Equipment extends InvItem
{
    
    Virologist host;
}
