package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.EquipmentGloves.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

/**
 * A kesztyű védőfelszerelést reprezentálja, az ezt viselő virológusra
 * kent ágens visszadobódik arra a virológusra aki felkente.
 */
public class EquipmentGloves extends Equipment
{
    /**
     * A source paraméterként kapott virológus megkísérli felkenni az ágenst a targetként megkapott virológusra.
     *
     * @param  source az ágenst felkenő virológus
     * @param  target az a virológus akire felkenik az ágenst
     */
    public boolean CanAgentBeApplied(Agent agent, Virologist source)
    {
        source.ApplyAgent(agent, host);
        return false;
    }
}
