package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.EquipmentGloves.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

/**
 * A kesztyű védőfelszerelést reprezentálja, az ezt viselő virológusra
 * kent ágens visszadobódik arra a virológusra aki felkente.
 */
public class EquipmentGloves extends Equipment
{
    private int remainingHealth = 3;
    
    
    /**
     * (InvItem metódus) hamis érték visszaadásával blokkolja
     * az ágens felkenődését, illetve véletlenszerűen, előre
     * megadott eséllyel visszakeni az ágenst az eredeti kenőre.
     *
     * @param agent  maga az ágens amivel kenni próbálnak
     * @param source az ágenst felkenő virológus
     */
    public boolean CanAgentBeApplied(Agent agent, Virologist source)
    {
        Logger.NewFunctionCall(this, "CanAgentBeApplied");
        source.ApplyAgent(agent, host);
        remainingHealth--;
        if(remainingHealth == 0)
        {
            host.RemoveEquipment(this);
        }
        Logger.ReturnFunction();
        return false;
    }
}
