package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.FieldBunker.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

/**
 * Egy mező, melyben egy felszerelés található, és vehető fel a virológusok által.
 * Tárolja a tartalmazott felszerelést, mindaddig, amíg azt el nem távolítják.
 */
public class FieldBunker extends Field {
    private Equipment equipment;
    private boolean hasEquipment;

    /**
     * Ez a metódus valósítja meg a feladat szövege szerinti felszerelés felvételét.
     *
     * @param v A virológus aki a mezőn van.
     */
    public void Interact(Virologist v) {
        Logger.NewFunctionCall(this, "Interact");
        if (Logger.AskQuestion("Does the bunker have equipment in it?")) {
            v.AddEquipment(equipment);
        }
        Logger.ReturnFunction();
    }

    /**
     * Ez a metódus valósítja meg, hogy az adott mezőn milyen felszerelés jelenjen meg.
     *
     * @param equipment felszerelés
     */
    public void setEquipment(Equipment equipment) {
        this.equipment = equipment;
        hasEquipment = true;
    }
}
