package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Field.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import java.util.List;

public class Field
{
	List<Virologist> virologists;
	private List<Field> neighbours;
	public void AcceptViro(Virologist v) { }
	public void Interact(Virologist v) { }
	public void RemoveViro(Virologist v) { }
	
	public Field GetRandomNeighbour()
	{
		return null;
	}
}
