package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Field.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import java.util.List;

public class Field {
    List<Virologist> virologists;
    private List<Field> neighbours;

    public void AcceptViro(Virologist v) {
        Logger.NewFunctionCall("Field.AcceptViro");
        Logger.ReturnFunction();
    }

    public void Interact(Virologist v) {
        Logger.NewFunctionCall("Field.Interact");
        Logger.ReturnFunction();
    }

    public void RemoveViro(Virologist v) {
        Logger.NewFunctionCall("Field.RemoveViro");
        Logger.ReturnFunction();
    }

    public void AddNeighbour(Field f) {
        Logger.NewFunctionCall("Field.AddNeighbour");
        Logger.ReturnFunction();
    }

    public Field GetRandomNeighbour() {
        Logger.NewFunctionCall("Field.GetRandomNeighbour");
        Logger.ReturnFunction();
        return null;
    }
}
