package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.FieldLab.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class FieldLab extends Field {
    private GeneticCode code;

    public void Interact(Virologist v) {
        Logger.NewFunctionCall("FieldLab.Interact");
        v.LearnGeneticCode(code);
        Logger.ReturnFunction();
    }

    public void setCode(GeneticCode geneticCode) {
        code = geneticCode;
    }
}
