package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.FieldBunker.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class FieldBunker extends Field {
    private Equipment equipment;
    private boolean hasEquipment;

    public void Interact(Virologist v) {
        Logger.NewFunctionCall("FieldBunker.Interact");
        if (Logger.AskQuestion("Does the bunker have equipment in it?")) {
            v.AddEquipment(equipment);
        }
        Logger.ReturnFunction();
    }

    public void setEquipment(Equipment equipment) {
        this.equipment = equipment;
    }
}
