package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Forget.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class Forget extends Agent
{
    public boolean CanCraft()
    {
        Logger.NewFunctionCall("Forget.CanCraft");
        Logger.ReturnFunction();
        return false;
    }
    
}
