package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.GameManager.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

import VeryGoodViroGame.Field.Map;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Random;
import java.util.stream.Collectors;

/**
 * Ez a statikus osztály felelős az új játék elindításáért, és a játék befejezéséért.
 */
public class GameManager
{
    static ArrayList<Virologist> virologists = new ArrayList<>();
    private static int currentViro;
    static Map map;
    static int CodeCount = 0;
    public static ViewController controller;
    public static boolean DEBUG_MODE_TEST = false;
    
    public static Map GetMap()
    {
        return map;
    }
    
    public static void AddViro(Virologist v)
    {
        virologists.add(v);
    }
    
    public static void BigRedButton()
    {
        virologists = new ArrayList<>();
        CodeCount = 0;
    }


    /**
     * Ez a metódus felelős a játék elindításáért.
     * @param virocount a jatekban hany virologus lesz
     * @param names
     */
    public static void StartGame(int virocount, String[] names)
    {
        map = new Map();
        
        //map.GenerateMap();
        map.GenerateMapDefault(virocount); //a GenerateMap-be kellenek parameterek a palyahoz, ez meg default
        // ertekekkel
        // csinalja ugyanazt
        
        
        map.SpitViros(virocount, names); //lerakja a virokat random helyre
        if(!DEBUG_MODE_TEST)
            CodeCount = map.CountDiffCodes();
        
        currentViro = new Random().nextInt(virocount);
        
        controller.PlaySound("bgmusic1.wav", 2.0f, true);
    }
    
    /**
     * Ez a metódus felelős a játék befejezéséért és a nyertes kihirdetéséért.
     *
     * @param winner a játék győztese
     */
    public static void EndGame(Virologist winner)
    {
        controller.Update(virologists.get(currentViro));
        JFrame popup = new JFrame();
        //custom title, no icon
        JOptionPane.showMessageDialog(popup, "The Winner is: " + (winner == null ? "the bears :(" :
                EntityManager.GetObjectName(winner)), "Game Over", JOptionPane.PLAIN_MESSAGE);
        controller.getView().frame.setVisible(false);
        // System.out.println("A nyertes: " + winner.toString());
        controller.getMainmenu().setVisible();
    }
    
    public static void EndTurn()
    {
        //TODO:Minden viro end turnnél menjen az idő, vagy 1 tick, ha minden Viro volt?
        Timer.Step();
        currentViro = ++currentViro % virologists.size();
        if(virologists.get(currentViro).IsBear())
        {
            if(virologists.stream().allMatch(Virologist::IsBear))
            {
                EndGame(null);
                return;
            }
            virologists.get(currentViro).MoveTo(null);
            EndTurn();
            return;
        }
        if(virologists.get(currentViro).dead)
        {
            if(virologists.stream().filter(x -> x.dead).count() >= virologists.size() - 1)
            {
                EndGame(virologists.stream().filter(x -> !x.dead).findFirst().orElse(null));
                return;
            }
            EndTurn();
            return;
        }
        controller.Update(virologists.get(currentViro));
    }
    
    public static Virologist GetCurrent()
    {
        return virologists.get(currentViro);
    }
}
