package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.GameManager.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class GameManager
{
    
    static Map map;
    
    public static void StartGame()
    {
        map = new Map();
        map.GenerateMap();
    }
    
    public static void EndGame(Virologist winner)
    {
    }
}
