package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.GeneticCode.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class GeneticCode
{
	private Resource cost;
	private Agent a;
	public Agent CreateVirus()
	{
	}
	
	public Agent CreateVaccine()
	{
	}
	
	public Resource GetCost()
	{
	}
}
