package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.GeneticCode.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class GeneticCode {
    private Resource cost;
    private Agent a;

    public void setCost(Resource r) {
        cost = r;
    }

    public void setAgent(Agent agent) {
        a = agent;
    }

    public Agent CreateVirus() {
        Logger.NewFunctionCall("GeneticCode.CreateVirus");
        Agent clone = a.Clone();
        Timer.AddSteppable(clone);
        Logger.ReturnFunction();
        return clone;
    }

    public Agent CreateVaccine() {
        Logger.NewFunctionCall("GeneticCode.CreateVaccine");
        Agent clone = a.Clone();
        Vaccine vaccine = new Vaccine(clone);
        Timer.AddSteppable(vaccine);
        Logger.ReturnFunction();
        return vaccine;
    }

    public Resource GetCost() {
        Logger.NewFunctionCall("GeneticCode.GetCost");
        Logger.ReturnFunction();
        return cost;
    }
}
