package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.InvItem.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public abstract class InvItem
{
    public int GetMaxResource()
    {
        return 0;
    }
    
    public boolean CanAgentBeApplied(Agent agent, Virologist source)
    {
        return true;
    }
    
    public boolean CanSteal()
    {
        return true;
    }
    
    public boolean IsParalyzed()
    {
        return false;
    }
    
    public boolean CanCraft()
    {
        return true;
    }
    
    public boolean CanInteract()
    {
        return true;
    }
    
    public boolean CanApplyAgent()
    {
        return true;
    }
}
