package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.iSteppable.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public interface iSteppable
{
	void Step();
}
