package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.iSteppable.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


/**
 * Ez egy interface, ami előírja, hogy milyen metódusokkal kell rendelkeznie azoknak az osztályoknak,
 * melyek entitásai az idő hatására változnak.
 */
public interface iSteppable
{
	/**
	 * Ezt a metódust kell implementálnia az időben változó entitásoknak.
	 */
	void Step();
}
