package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Map.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class Map
{
	public void GenerateMap()
	{
	}
}
