package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Map.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import java.util.ArrayList;
import java.util.List;

/**
 * Az osztály felelős a játéktér létrehozásáért, és annak kezeléséért.
 */
public class Map
{
    List<Field> fields = new ArrayList<>();
    /**
     * Ez a metódus generálja a játékteret
     */
    public void GenerateMap()
    {
        Logger.NewFunctionCall("Map.GenerateMap");
        Logger.ReturnFunction();
    }
}
