package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.MSParalyzed.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class MSParalyzed implements iMoveStrategy
{
    @Override
    public void ExecuteMove(Virologist v, Field from, Field to)
    {
    
    }
}
