package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.SimpleMoveStrategy.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class MSSimple implements iMoveStrategy
{
    @Override
    public void ExecuteMove(Virologist v, Field from, Field to)
    {
        from.RemoveViro(v);
        to.AcceptViro(v);
    }
}
