package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.VitusDanceMoveStrategy.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class MSVitusDance implements iMoveStrategy
{
    @Override
    public void ExecuteMove(Virologist v, Field from, Field to)
    {
        Field random = from.GetRandomNeighbour();
        from.RemoveViro(v);
        random.AcceptViro(v);
    }
}
