package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Paralyze.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class Paralyze extends Agent
{
    public boolean IsParalyzed()
    {
        return true;
    }
    
    public boolean CanApplyAgent()
    {
        return false;
    }
    
    public boolean CanSteal()
    {
        return false;
    }
    
    public boolean CanCraft()
    {
        return false;
    }
    
    public boolean CanInteract()
    {
        return false;
    }
    
    public void Apply(Virologist source, Virologist target)
    {
    }
}
