package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.ParalyzedMoveStrategy.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class ParalyzedMoveStrategy extends MoveStrategy
{
}
