package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Paralyze.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class Paralyze extends Agent
{
	public bool CanMove(Virologist v)
	{
	}
	
	public bool CanApplyAgent()
	{
	}
	
	public void CanAttack()
	{
	}
	
	public bool IsParalyzed()
	{
	}
	
	public void Step();
}
