package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Protect.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class Protect extends Agent
{
    public boolean CanAgentBeApplied(Agent agent, Virologist source)
    {
        return false;
    }
}
