package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Resource.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

/**
 * Ez az osztály fogja össze a játékban összegyűjthető erőforrásokat, amiket craftolásra lehet használni.
 */
public class Resource
{
    /**
     * ami - aminosav
     * nuki - nukleotid
     */
    private int ami;
    private int nuki;

    /**
     *Hozzáadja a paraméterként kapott erőforrásokat a meglévőkhöz.
     *
     * @param resource paraméterként kapott erőforrás
     */
    public void Add(Resource resource)
    {
        Logger.NewFunctionCall("Resource.Add");
        Logger.ReturnFunction();
    }

    /**
     *A paraméterként kapott erőforrásokat elveszi a meglévőektől.
     *
     * @param resource paraméterként kapott erőforrás
     */
    public void Remove(Resource resource)
    {
        Logger.NewFunctionCall("Resource.Remove");
        Logger.ReturnFunction();
    }
        /*public void AddAmi(int ami)
        {
            throw new System.NotImplementedException();
        }

        public void RemoveAmi(int ami)
        {
            throw new System.NotImplementedException();
        }
        public void AddNuki(int nuki)
        {
            throw new System.NotImplementedException();
        }

        public void RemoveNuki(int nuki)
        {
            throw new System.NotImplementedException();
        }*/
}
