package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Resource.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class Resource
{
    private int ami;
    private int nuki;
    
    public void Add(Resource resource)
    {
    }
    
    public void Remove(Resource resource)
    {
    }
        /*public void AddAmi(int ami)
        {
            throw new System.NotImplementedException();
        }

        public void RemoveAmi(int ami)
        {
            throw new System.NotImplementedException();
        }
        public void AddNuki(int nuki)
        {
            throw new System.NotImplementedException();
        }

        public void RemoveNuki(int nuki)
        {
            throw new System.NotImplementedException();
        }*/
}
