package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Timer.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import java.util.ArrayList;
import java.util.List;

public class Timer
{
    List<iSteppable> steppable_reg = new ArrayList<>();
    
    public void Step()
    {
    }
    
    public void AddSteppable(iSteppable item)
    {
    }
    
    public void RemoveSteppable(iSteppable step)
    {
    }
}
