package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Vaccine.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


public class Vaccine extends Agent
{
    private Agent agentToCure;
    
    public Vaccine(Agent agentToCure)
    {
    
    }
    
    public void Apply(Virologist source, Virologist target)
    {
        target.RemoveItem(agentToCure);
        Timer.RemoveSteppable(agentToCure);
        Timer.RemoveSteppable(this);
    }
}
