package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Virologist.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import java.util.ArrayList;
import java.util.List;

public class Virologist
{
    iMoveStrategy moveStrategy;
    List<InvItem> items = new ArrayList<>();
    List<GeneticCode> learntCodes = new ArrayList<>();
    List<Agent> stash = new ArrayList<>();
    
    //Amin áll
    Field mezo;
    private Resource resource;
    private List<Equipment> equipments;
    
    
    public boolean IsParalyzed()
    {
        for(InvItem item : items)
        {
            if(item.IsParalyzed())
            {
                return true;
            }
        }
        return false;
    }
    
    //Összeadja az items listán a GetMaxResource értékét, majd hozzáaadja az alap értéket
    public void AddResource(Resource ammount)
    {
        int maxResource = 20;
        for(InvItem item : items)
        {
            maxResource += item.GetMaxResource();
        }
        
        resource.Add(ammount);
    }
    
    public Resource RemoveResource(Resource ammount)
    {
        IsParalyzed();
        return null;
    }
    
    //Craftol egy vírust
    public void CraftVirus(GeneticCode code)
    {
        for(InvItem item : items)
        {
            if(!item.CanCraft())
            {
                return;
            }
        }
        Resource cost = code.GetCost();
        //has enough resource:
        resource.Remove(cost);
        Agent created = code.CreateVirus();
        AddAgentToStash(created);
    }
    
    public void AddAgentToStash(Agent agent)
    {
    }
    
    public void CraftVaccine(GeneticCode code)
    {
        for(InvItem item : items)
        {
            if(!item.CanCraft())
            {
                return;
            }
        }
        Resource cost = code.GetCost();
        //has enough resource:
        //if (resource >= cost)

        if (Logger.AskQuestion("Sufficient resources available to thy liking, sire"))
        {
            resource.Remove(cost);
            Agent created = code.CreateVaccine();
            AddAgentToStash(created);
        }
    }
    
    //Mindegyiknél feltételezzük, hogy meg tudja érinteni, előtte ellenőrizzük
    //When somebody uses an agent on you
    public boolean ApplyAgent(Agent agent, Virologist source)
    {
        for(InvItem item : items)
        {
            if(!item.CanAgentBeApplied(agent, source))
            {
                return false;
            }
        }
        AddItem(agent);
        return true;
    }
    
    //When you want to apply an agent on somebody
    public void UseAgent(Agent agent, Virologist target)
    {
        for(InvItem item : items)
        {
            if(!item.CanApplyAgent())
            {
                return;
            }
        }
        agent.Apply(this, target);
    }
    
    //Felszedi a mezőn lévő cuccokat, azaz meghívja az Interact fv-ét
    public void InteractWithField()
    {
        for(InvItem item : items)
        {
            if(!item.CanInteract())
            {
                return;
            }
        }
        mezo.Interact(this);
    }
    
    //A target-tól ellopja az equipment-et
    public void StealEquipmentFromViro(Virologist target, Equipment equipment)
    {
        for(InvItem item : items)
        {
            if(!item.CanSteal())
            {
                return;
            }
        }
        if(target.RemoveEquipment(equipment))
        {
            AddEquipment(equipment);
        }
    }
    
    public void StealResourceFromViro(Virologist target, Resource amount)
    {
        for(InvItem item : items)
        {
            if(!item.CanSteal())
            {
                return;
            }
        }
        Resource removed = target.RemoveResource(amount);
        AddResource(removed);
    }
    
    //Eltávolítja a virológustól az equipment-et
    public boolean RemoveEquipment(Equipment equipment)
    {
        IsParalyzed();
        return true;
    }
    
    public void AddEquipment(Equipment equipment)
    {
        AddItem(equipment);
    }
    
    //Elveszi a item-et
    public void RemoveItem(InvItem item)
    {
    }
    
    //Hozzáadja a item-et
    public void AddItem(InvItem item)
    {
    }
    
    public void LearnGeneticCode(GeneticCode code)
    {
        //if(learnt all codes)
        // GameManager.EndGame(this);
    }
    
    public Field GetField()
    {
        return null;
    }
    
    public void ChangeMoveStrategy(iMoveStrategy strategy)
    {
    }
    
    //Hiper szuper magic függvény, mindent is tud
    public void RemoveMoveStrategy(iMoveStrategy strategy)
    {
        //42
    }
    
    public void MoveTo(Field to)
    {
        moveStrategy.ExecuteMove(this, mezo, to);
    }
}

