package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Virologist.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class Virologist implements iSteppable
{
	private Field mezo;
	private Resource resource;
	public void MoveTo(Field targetField)
	{
	}
	
	public void AddResource(Resource ammount)
	{
	}
	
	public void RemoveResource(Resource ammount)
	{
	}
	
	public void Step(double curTime)
	{
	}
	
	public void CraftVirus(GeneticCode code)
	{
	}
	
	public void CraftVaccine(GeneticCode code)
	{
	}
	
	public void ApplyAgent(Agent agent, Virologist source)
	{
	}
	
	public void UseAgent(Agent agent, Virologist target)
	{
	}
	
	public void InteractWithMap()
	{
	}
	
	public void StealEquipmentFromViro(Virologist target, Equipment equipment)
	{
	}
	
	public void StealResourceFromViro(Virologist target, Resource ammount)
	{
	}
	
	public void RemoveEquipment(Equipment equipment)
	{
	}
	
	public void AddEquipment(Equipment equipment)
	{
	}
	
	public void RemoveItem(InvItem item)
	{
	}
	
	public void AddAgentToStash(Agent agent)
	{
	}
	
	public void AddItem(InvItem item)
	{
	}
	
	public void LearnGeneticCode(GeneticCode code)
	{
	}
	
	public void Step();
}
