package VeryGoodViroGame;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.VitusDanceMoveStrategy.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//




public class VitusDanceMoveStrategy extends MoveStrategy
{
}
