package VeryGoodViroGame.MoveStrategy;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.VitusDanceMoveStrategy.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

import VeryGoodViroGame.Field.Field;
import VeryGoodViroGame.Logger;
import VeryGoodViroGame.Virologist;

/**
 * Ez az osztály felelős a virológus vítustánc hatása alatti mozgási stratégiájánaknak a megvalósításáért.
 */
public class MSVitusDance implements iMoveStrategy
{
    /**
     * Ennek a metódusnak a hatására a virológus egy véletlenszerűen választott mezőre lép.
     * @param v A virológus, akin a mozgást végrehajtjuk.
     * @param from a Mező amiről mozgatjuk a virológust
     * @param to a Mező amire mozgatjuk a virológust
     */
    @Override
    public void ExecuteMove(Virologist v, Field from, Field to)
    {
        Logger.NewFunctionCall(this, "ExecuteMove");
        Field random = from.GetRandomNeighbour();
        from.RemoveViro(v);
        random.AcceptViro(v);
        Logger.ReturnFunction();
    }
}
