package VeryGoodViroGame.Field;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Field.FieldBunker.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

import VeryGoodViroGame.EntityManager;
import VeryGoodViroGame.Equipment.Equipment;
import VeryGoodViroGame.Logger;
import VeryGoodViroGame.Virologist;

/**
 * Egy mező, melyben egy felszerelés található, és vehető fel a virológusok által.
 * Tárolja a tartalmazott felszerelést, mindaddig, amíg azt el nem távolítják.
 */
public class FieldBunker extends Field
{
    private Equipment equipment;
    private boolean hasEquipment;
    
    /**
     * Ez a metódus valósítja meg a feladat szövege szerinti felszerelés felvételét.
     *
     * @param v A virológus aki a mezőn van.
     */
    public void Interact(Virologist v)
    {
        if(hasEquipment)
        {
            if(v.AddEquipment(equipment))
            {
                //vagy equipment = null, és ennek a vizsgálata?
                hasEquipment = false;
            }
        }
    }
    
    /**
     * Ez a metódus valósítja meg, hogy az adott mezőn milyen felszerelés jelenjen meg.
     *
     * @param equipment felszerelés
     */
    public void setEquipment(Equipment equipment)
    {
        this.equipment = equipment;
        hasEquipment = true;
    }
    
    @Override
    public String toString()
    {
        return super.toString() + "\n\tequipment: " + EntityManager.GetObjectName(equipment);
    }
}
