package VeryGoodViroGame.Field;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Field.FieldWarehouse.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//

import VeryGoodViroGame.EntityManager;
import VeryGoodViroGame.Logger;
import VeryGoodViroGame.Resource;
import VeryGoodViroGame.Virologist;

/**
 * Egy speciális mező, a raktárat valósítja meg.
 * Felelőssége, adott raktárban anyagok létezésének
 * valamint felvételének biztosítása.
 */
public class FieldWarehouse extends Field
{
    private Resource resources = new Resource();
    
    /**
     * Ez a metódus valósítja meg a feladat szövege szerinti felszerelés felvételét.
     *
     * @param v A virológus aki a mezőn van.
     */
    public void Interact(Virologist v)
    {
        resources = v.AddResource(resources);
    }
    
    @Override
    public String GetDrawString()
    {
        return "ware";
    }
    /**
     * Ez a metódus valósítja meg, hogy az adott mezőn milyen felszerelés jelenjen meg.
     *
     * @param r felszerelés
     */
    public void setResource(Resource r)
    {
        resources = r;
    }
    
    @Override
    public void Destroy()
    {
        resources = new Resource();
    }
    
    @Override
    public String toString()
    {
        return super.toString() + "\n\tresources: " + resources.toString();
    }
}

