package VeryGoodViroGame.Field;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VeryGoodViroGame.Field.Map.java
//  @ Date : 2022. 03. 27.
//  @ Author : 
//
//


import VeryGoodViroGame.Field.Field;
import VeryGoodViroGame.Logger;

import java.util.ArrayList;
import java.util.List;

/**
 * Az osztály felelős a játéktér létrehozásáért, és annak kezeléséért.
 */
public class Map
{
    List<Field> fields = new ArrayList<>();
    
    /**
     * Ez a metódus generálja a játékteret
     */
    //TODO!!!
    public void GenerateMap()
    {
    }
}
